### ISSUE TITLE
Does not support multiple subscribers

### ISSUE THREAD

**Issue by sid-code** [edoceo/httpubsub#4]
So, I'm running it:

```bash
$ go run httppubsub.go &
```

Then, in two separate instances:

```bash
$ while true; do curl localhost:8080/testpipe; done
```

Then, when I publish something with a POST request, it only comes out of one of the subscribers.

**Comment by sid-code** [comment]
I should add that I fully expected it to not work after reading the code. I'm trying to figure out how to implement it right now, but I thought I'd post it here to get comments.

**Comment by djbusby** [comment]
Right now, the 1<->1 issue is (I think) following the observed behaviour of the inspiration -- except with their PubSub parameter to the POST option.  This is something I think I'll have to figure out how to implement.

```
When I have created multiple subscribers to a single channel
And I have POSTed a single message to the channel -- perhaps with a flag.
Then all existing subscribers should receive the message.
```

**Comment by olup** [comment]
I implemented a pubsub only version myself : https://github.com/olup/patchcreek

**Comment by djbusby** [comment]
I've got a (yet un-pushed) branch that is working on this part, as well as some timeout functions as well.

**Comment by djbusby** [comment]
This is fixed in https://github.com/edoceo/httpubsub/commit/916f3b81343dd24e69e457eaee523b4d6206654d
I refactored the code a bit so the data-classes are easier to grok.
WOMM :)
